server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_S3_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
    mongodb:
      uri: mongodb://localhost:27017
      database: chatapp

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mappers/**/*.xml

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
  client-id: ${YOUTUBE_CLIENT_ID}
  client-secret: ${YOUTUBE_CLIENT_SECRET}
  redirect-uri: ${YOUTUBE_REDIRECT_URI}

facebook:
  client-id: ${FACEBOOK_CLIENT_KEY}
  client-secret: ${FACEBOOK_CLIENT_SECRET}
  redirect-uri: ${FACEBOOK_REDIRECT_URI}
  base-url: https://graph.facebook.com/v23.0

google:
  sheet:
    credentials: credentials.json
    spreadsheet-id: ${SHEET_ID}

naver:
  client-id: ${NAVER_CLIENT_KEY}
  client-secret: ${NAVER_CLIENT_SECRET}